spring:
  application:
    name: pokemon-api

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:pokemon}
    username: ${POSTGRES_USER:alea}
    password: ${POSTGRES_PASSWORD:alea}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    com.alea.pokemon: DEBUG

alea:
  pokeapi:
    base-url: https://pokeapi.co/api/v2